config/routes.rb
Rails.application.routes.draw do
  root 'application#root'

  get '/gallery', to: 'application#gallery'

  resources :contacts, only: [:create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :phone, :validate => true
  attribute :email, :validate => true
  attribute :message, :validate => true

  def headers
    {
      :subject => "Williams Contact From Site",
      :to => "michael.james.randell@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def root
    @contact = Contact.new
  end

  def gallery
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        #format.html
        format.js
      else

      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">561-967-1591</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to "Home", root_path %>
                </li>
                <li>
                    <%= link_to "Gallery", gallery_path %>
                </li>
                <li>
                    <a href="#" data-toggle="modal" data-target="#myModal">Message</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

app/views/application/gallery.html.erb
<div class="gallery">

<div class="montserrat text-center space-gallery">
  <h1><b>Check out our work!</b></h1>
</div>

<div class="row">
    <div class="offset-md-2 col-md-12">
        <div class="row space-gallery">
            <a href="https://unsplash.it/1200/768.jpg?image=251" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4">
                <img src="https://unsplash.it/600.jpg?image=251" class="img-fluid img-fitter">
            </a>
            <a href="https://unsplash.it/1200/768.jpg?image=252" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4">
                <img src="https://unsplash.it/600.jpg?image=252" class="img-fluid img-fitter">
            </a>
            <a href="https://s3.us-east-2.amazonaws.com/williamssimple/MeanGreenSodMachineV3.jpg" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4">
                <img src="https://s3.us-east-2.amazonaws.com/williamssimple/MeanGreenSodMachineV3.jpg" class="img-fluid img-fitter">
            </a>
        </div>
        <div class="row space-gallery">
            <a href="https://s3.us-east-2.amazonaws.com/williamssimple/SodRemoval.jpg" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4">
                <img src="https://s3.us-east-2.amazonaws.com/williamssimple/SodRemoval.jpg" class="img-fluid img-fitter">
            </a>
            <a href="https://s3.us-east-2.amazonaws.com/williamssimple/SodLayers1.jpg" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4">
                <img src="https://s3.us-east-2.amazonaws.com/williamssimple/SodLayers1.jpg" class="img-fluid img-fitter">
            </a>
            <a href="https://s3.us-east-2.amazonaws.com/williamssimple/SodLayers2.jpg" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4">
                <img src="https://s3.us-east-2.amazonaws.com/williamssimple/SodLayers2.jpg" class="img-fluid img-fitter">
            </a>
        </div>
        <div class="row space-gallery">
            <a href="https://unsplash.it/1200/768.jpg?image=254" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4">
                <img src="https://unsplash.it/600.jpg?image=254" class="img-fluid img-fitter">
            </a>
            <a href="https://unsplash.it/1200/768.jpg?image=255" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4">
                <img src="https://unsplash.it/600.jpg?image=255" class="img-fluid img-fitter">
            </a>
            <a href="https://unsplash.it/1200/768.jpg?image=256" data-toggle="lightbox" data-gallery="example-gallery" class="col-sm-4">
                <img src="https://unsplash.it/600.jpg?image=256" class="img-fluid img-fitter">
            </a>
        </div>
    </div>
</div>
</div>

<script>
  $(document).on('click', '[data-toggle="lightbox"]', function(event) {
      event.preventDefault();
      $(this).ekkoLightbox();
  });
</script>

app/views/application/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">561-967-1591</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Image Background Page Header -->
<!-- Note: The background image is set within the business-casual.css file. -->
<header class="business-header">
    <div class="container">
        <div class="row">
          <div class="col">
              <h1 class="tagline">Williams Soils & Sod</h1>


              <h5 class="tagline-statement">Serving South Florida for Over 50 Years</h5>
            </div>
        </div>
    </div>
</header>

<!-- Page Content -->
<div class="container">

    <hr>


    <div class="row">
        <div class="col-sm-8 montserrat">
            <h2>What We Do</h2>
            <p>We take care of your sodding needs from the planning stage to implementation. In the process, we are guided by your individual wishes, needs and interests, as well as the landscape's character. Resulting in a harmonious concept. And most importantly, when it comes to our product, <b class="red">we always prioritize quality.</b></p>
            <p>We are a family business and have been based out of West Palm Beach for over 50 years, serving all of South Florida.  We are extremely familiar with the needs of the Local Residents, Builders and Landscapers for quality sod and dependable service. No job is too big or too small, for both commerial and residential projects.</p>
            <p>
                <a class="btn btn-default btn-lg" href="#">Schedule a Free Estimate &raquo;</a>
            </p>
        </div>
        <div class="col-sm-4">
            <h2>Contact Us</h2>
            <address>
                <strong>Williams Soils & Sod</strong>
                <br>2580 S Military Trail
                <br>West Palm Beach, FL 33415
                <br>
            </address>
            <address>
                <abbr title="Phone"></abbr><b>(561) 967-1591</b>
                <br>
                <abbr title="Email"></abbr> <a href="mailto:#">williamssod@comcast.net</a>
            </address>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src="https://s3.us-east-2.amazonaws.com/williamssimple/WilliamsProductV3.jpg" alt="">
            <h2>Our Product</h2>
            <p>Quality is always our #1 priority, we are always researching and in connection with our sod farms in Belle Glade. The soil east of Lake Okechobee is called 'Black Gold', some of the most fertile soil in the nation.</p>
        </div>
        <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src="https://s3.us-east-2.amazonaws.com/williamssimple/GreenMeanSodMachineV2.jpg" alt="">
            <h2>The Mean Green Sod Machine</h2>
            <p>We run two trucks, with our latest upgrade, The Mean Green Sod Machine. We can deliver your sod quickly and effectively, moving sod where you need it.</p>
        </div>
        <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src="https://s3.us-east-2.amazonaws.com/williamssimple/WilliamsBigJob.jpg" alt="">
            <h2>No job is too big or too small</h2>
            <p>We have the resources to handle any size job. Residential or commercial, no job is too big or too small for use.</p>
        </div>
    </div>


    <hr>


    <footer>
    </footer>

</div>

app/views/application/root.html.erb
<header class="business-header">
    <div class="container">
        <div class="row">
          <div class="col">
              <h1 class="tagline">Williams Soils & Sod</h1>


              <h5 class="tagline-statement">Family Business Serving South Florida for Over 60 Years</h5>
            </div>
        </div>
    </div>
</header>

<!-- Page Content -->
<div class="container">

    <hr>


    <div class="row">
        <div class="col-sm-8 montserrat">
            <h1>What We Do</h1>
            <p>We take care of your sodding needs from the planning stage to implementation. In the process, we are guided by your individual wishes, needs and interests, as well as the landscape's character. Resulting in a harmonious concept. And most importantly, when it comes to our product, <b class="red">we always prioritize quality.</b></p>
            <p>We are a family business and have been based out of West Palm Beach for over 60 years, serving all of South Florida.  We are extremely familiar with the needs of the Local Residents, Builders and Landscapers for quality sod and dependable service. No job is too big or too small, for both commerial and residential projects.</p>
            <p>
              <button type="button" class="btn btn-lg" data-toggle="modal" data-target="#myModal">Schedule A Free Estimate!</button>
              <div id="myModal" class="modal fade" role="dialog">
                <%= render :partial => 'contacts/contact_form' %>
              </div>
            </p>
        </div>
        <div class="col-sm-4 montserrat">
            <h1>Contact Us</h1>
            <address>
                <strong>Williams Soils & Sod</strong>
                <br>2580 S Military Trail
                <br>West Palm Beach, FL 33415
                <br>
            </address>
            <address>
                <abbr title="Phone"></abbr><strong class="red phone-size">(561) 967-1591</strong>
                <br>
                <abbr title="Email"></abbr> <a class="red" href="mailto:williamssod@comcast.net">williamssod@comcast.net</a>
            </address>
        </div>
    </div>

    <hr>

    <div class="row montserrat">
        <div class="col-sm-4 img-col">
            <img class="img-circle img-responsive img-center" src="https://s3.us-east-2.amazonaws.com/williamssimple/WilliamsProduct.jpg" alt="">
            <h2>Our Product</h2>
            <p><b class="red">Quality is always our #1 priority</b>, always researching and in connection with our sod farms in Belle Glade. The soil east of Lake Okechobee is called 'Black Gold', some of the most fertile soil in the nation.</p>
            <p>We offer St. Augstine Floratam, Palmetto, Bermuda, Zoysia, Paspalum and Bahia varieties. We also stock Topsoil, Fill, Mulch, Sand and Gravel at our conveniently located facility in West Palm Beach.</p>
        </div>
        <div class="col-sm-4 img-col">
            <img class="img-circle img-responsive img-center" src="https://s3.us-east-2.amazonaws.com/williamssimple/GreenMeanSodMachineV2.jpg" alt="">
            <h2>Our Services</h2>
            <p><b class="red">From consultation, to delivery, to installation, we handle all aspects of your project.</b> Taking into consideration your individual needs and creative aspirations, we can help with professional guidance to see your project through.</p>
            <p>We run two trucks, with our latest upgrade, 'The Mean Green Sod Machine.' <b class="red">We deliver your sod quickly and effectively</b>, moving sod where you need it. Removal and installation is handled as well, with our team of experienced sod layers.</p>
        </div>
        <div class="col-sm-4 img-col">
            <img class="img-circle img-responsive img-center" src="https://s3.us-east-2.amazonaws.com/williamssimple/WilliamsBigJob.jpg" alt="">
            <h2>Our Resources</h2>
            <p>We have the resources to handle any size job. Residential or commercial, <b class="red">no job is too big or too small for us.</b> We have the connections and have built our team up for many years now.</p>
        </div>
    </div>


    <hr>

    <div class="text-center strong montserrat">
      <%= link_to 'See Our Work!', gallery_path, :class => 'btn btn-block btn-lg strong' %>
    </div>


    <footer>
    </footer>

</div>

app/views/contacts/_contact_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h1 class="modal-title red">Send us a message!</h1>
    </div>
    <div class="modal-body">
      <h4 class="page_title dark-green">Please provide us with details!</h4>
      <%= form_for @contact, remote: true, :html=> {:class => 'form-group'} do |f| %>
        <%= @contact.errors.full_messages.join(', ') %>

        <%= f.text_field :name, placeholder: 'name', required: true, class: 'form-control name' %>
        <%= f.telephone_field :phone, placeholder: 'phone number', required: true, class: 'form-control phone' %>
        <%= f.email_field :email, placeholder: 'email', required: true, class: 'form-control email' %>
        <%= f.text_area :message, placeholder: 'please provide us with all the details of your inquiry', class: 'form-control message' %>
        <%= f.submit 'Send', class: 'btn btn-default contact-submit'%>
      <% end %>
      <h4 class="contact-message"></h4>
    </div>
  </div>
</div>

app/views/contacts/_success_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h1 class="modal-title">Thank you! We will be in contact ASAP!</h1>
    </div>
  </div>
</div>

app/views/contacts/create.js.erb
//$('.modal-content').replaceWith(`<div class="modal-dialog">
//  <div class="modal-content">
//    <div class="modal-header">
//      <button type="button" class="close" data-dismiss="modal">&times;</button>
//      <h1 class="modal-title">We will be in contact ASAP!</h1>
//    </div>
//  </div>
//</div>`)

$('.contact-message').html(`Great! We will be in touch ASAP!`)


//$('#myModal').hide()

//$('#myModal').on('hidden', function () {
  // Load up a new modal...
//  $('#successModal').show()
//})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Williams</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= render partial: "navbar" %>
    <%= yield %>
  </body>


</html>